@baseUrl = http://0.0.0.0:10000/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1NzI4Y2ZjMTRkMDYzMDlmMjAwMjUiLCJ1c2VyIjoiYWxpIiwiaWF0IjoxNzY1MTg4MjA5LCJleHAiOjE3NjUxOTU0MDl9.5fewWTBInFI5CnEmU8Is0AyH7BUjQFibiOBqdWFx27Y

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "ali",
    "password": "123",
    "email": "dfdfd"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json


{
    "username": "ali",
    "password": "123"
}

###
POST {{baseUrl}}/upload
Content-Type: multipart/form-data
Authorization: {{token}}
# test this with other applications

###
GET {{baseUrl}}/upload
Authorization: {{token}}

###
GET {{baseUrl}}/upload/7878e5db-a3e7-4350-ae11-8758b17e8e86
Authorization: {{token}}

###
PUT {{baseUrl}}/upload/df6356b1-0305-4b0d-afe8-72d1c3d6bbd9
Authorization: {{token}}
Content-Type: multipart/form-data
# test this with other applications

###
DELETE {{baseUrl}}/upload/f20645bf-a615-4d5c-91c0-edc26a543861
Authorization: {{token}}

###
GET {{baseUrl}}/strategy

###
GET {{baseUrl}}/strategy/Sharif-WM
