POST http://0.0.0.0:10000/api/auth/register
Content-Type: application/json

{
    "username": "ali",
    "password": "123",
    "email": "dfdfd"
}

###
POST http://0.0.0.0:10000/api/auth/login
Content-Type: application/json

{
    "username": "ali",
    "password": "123"
}
