@baseUrl = http://0.0.0.0:10000/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1NzI4Y2ZjMTRkMDYzMDlmMjAwMjUiLCJ1c2VyIjoiYWxpIiwiaWF0IjoxNzY1MjgzNDMwLCJleHAiOjE3NjUyOTA2MzB9.ub4SHiO6BsP2wRdoacSCUSQ5olfABp-LoiaDBwg7Hvc

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "ali",
    "password": "123",
    "email": "dfdfd"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json


{
    "username": "ali",
    "password": "123"
}

###
POST {{baseUrl}}/upload
Content-Type: multipart/form-data
Authorization: {{token}}
# test this with other applications

###
GET {{baseUrl}}/upload
Authorization: {{token}}

###
GET {{baseUrl}}/upload/214991ac-956c-4c1f-8e93-9e7ac479ed69
Authorization: {{token}}

###
PUT {{baseUrl}}/upload/df6356b1-0305-4b0d-afe8-72d1c3d6bbd9
Authorization: {{token}}
Content-Type: multipart/form-data
# test this with other applications

###
DELETE {{baseUrl}}/upload/f20645bf-a615-4d5c-91c0-edc26a543861
Authorization: {{token}}

###
GET {{baseUrl}}/strategy

###
GET {{baseUrl}}/strategy/Sharif-WM

###
POST {{baseUrl}}/apply/Sharif-WM
Content-Type: application/json
Authorization: {{token}}

{
    "base": "214991ac-956c-4c1f-8e93-9e7ac479ed69",
    "watermark": "123"
}